"""update_manner_history_add_columns

Revision ID: b91fe51169d6
Revises: 23c23f355635
Create Date: 2026-06-09 15:09:15.955514

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "b91fe51169d6"
down_revision: Union[str, None] = "23c23f355635"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE mannerfactorenum ADD VALUE IF NOT EXISTS 'image_analysis'")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
